require('../scss/main.scss')
require('./disableIe.js')()
require('./disableMobile.js')()
require('./waypoint.js')()
require('./lazyLoad.js')()
require('./hamburger.js')()
require('./carousel.js')()
require('./triggerPie.js')()
