require('./disableIe.js')();
require('./disableMobile.js')();
require('./cookiePolicy.js')();
require('./waypoint.js')();
require('./lazyLoad.js')();
require('./hamburger.js')();
require('./postForm.js')();
require('./carousel.js')();
require('./triggerPie.js')();
